sfmrabbit:
    image: rabbitmq@sha256:397382d2b222f3a298a6c74e93f348fb16f9a7fde2c02ba14122624d852daae3
    #RabbatMQ 3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - TZ=EST
        - RABBITMQ_DEFAULT_USER=sfm_user
    env_file:
        - ./secrets.env
sfmdb:
    image: gwul/sfm-ui-db:master
    env_file:
        - ./secrets.env
    environment:
        - TZ=EST
    restart: always
sfmuiapp:
    image: gwul/sfm-ui:master
    ports:
        - "80:80"
    links:
        - sfmdb:db
        - sfmrabbit:mq
    environment:
        - TZ=EST
        - SFM_DEBUG=True
        - SFM_SITE_ADMIN_EMAIL=nowhere@example.com
    restart: always
    volumes_from:
        - sfmdata
sfmflickrharvester:
    image: gwul/sfm-flickr-harvester:master
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=EST
        - DEBUG=True
    volumes_from:
        - sfmdata
sfmflickrexporter:
    image: gwul/sfm-flickr-exporter:master
    links:
        - sfmrabbit:mq
        - sfmuiapp:api
    restart: always
    environment:
        - DEBUG=True
    volumes_from:
        - sfmdata
sfmtwitterrestharvester:
    image: gwul/sfm-twitter-rest-harvester:master
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=EST
        - DEBUG=True
    volumes_from:
        - sfmdata
sfmtwitterstreamharvester:
    image: gwul/sfm-twitter-stream-harvester:master
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=EST
        - DEBUG=True
    volumes_from:
        - sfmdata
sfmweiboharvester:
    image: gwul/sfm-weibo-harvester:master
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=EST
        - DEBUG=True
    volumes_from:
        - sfmdata
sfmheritrix:
    image: gwul/sfm-heritrix:master
    ports:
        - "8443:8443"
    env_file:
        - ./secrets.env
    environment:
        - TZ=EST
    volumes_from:
        - sfmdata
    restart: always
sfmwebharvester:
    image: gwul/sfm-web-harvester:master
    links:
        - sfmrabbit:mq
        - sfmheritrix:heritrix
    environment:
        - TZ=EST
        - DEBUG=True
        - HERITRIX_CONTACT_URL=http://library.gwu.edu
    volumes_from:
        - sfmheritrix
    restart: always
sfmdata:
    image: ubuntu:14.04
    command: /bin/true
    volumes:
         - /sfm-data