sfmrabbit:
    image: rabbitmq@sha256:397382d2b222f3a298a6c74e93f348fb16f9a7fde2c02ba14122624d852daae3
    #RabbitMQ 3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - TZ=EST
        - RABBITMQ_DEFAULT_USER=sfm_user
    # From secrets.env, get rabbit user password.
    env_file:
        - ./secrets.env
sfmdb:
    image: gwul/sfm-ui-db:master
    environment:
        - TZ=EST
    # From secrets.env, get postgres password.
    env_file:
        - ./secrets.env
    restart: always
sfmuiapp:
    image: gwul/sfm-ui:master
    ports:
        - "80:80"
    links:
        - sfmdb:db
        - sfmrabbit:mq
    environment:
        - TZ=EST
        - SFM_DEBUG=False
        - SFM_HOST=sfm.gwu.edu:8080
        - SFM_SMTP_HOST=smtp.gmail.com
        - SFM_SITE_ADMIN_EMAIL=nowhere@example.com
    # From secrets.env, get email configuration and site admin password.
    # Also, optionally get twitter and weibo credentials.
    env_file:
        - ./secrets.env
    restart: always
    volumes_from:
        - sfmdata
sfmflickrharvester:
    image: gwul/sfm-flickr-harvester:master
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=EST
        - DEBUG=True
    volumes_from:
        - sfmdata
sfmflickrexporter:
    image: gwul/sfm-flickr-exporter:master
    links:
        - sfmrabbit:mq
        - sfmuiapp:api
    restart: always
    environment:
        - DEBUG=True
    volumes_from:
        - sfmdata
sfmtwitterrestharvester:
    image: gwul/sfm-twitter-rest-harvester:master
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=EST
        - DEBUG=True
    volumes_from:
        - sfmdata
sfmtwitterstreamharvester:
    image: gwul/sfm-twitter-stream-harvester:master
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=EST
        - DEBUG=True
    volumes_from:
        - sfmdata
sfmweiboharvester:
    image: gwul/sfm-weibo-harvester:master
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=EST
        - DEBUG=True
    volumes_from:
        - sfmdata
sfmheritrix:
    image: gwul/sfm-heritrix:master
    ports:
        - "8443:8443"
    environment:
        - TZ=EST
        - HERITRIX_USER=sfm_user
    # From secrets.env, get heritrix user password.
    env_file:
        - ./secrets.env
    volumes_from:
        - sfmdata
    restart: always
sfmwebharvester:
    image: gwul/sfm-web-harvester:master
    links:
        - sfmrabbit:mq
        - sfmheritrix:heritrix
    environment:
        - TZ=EST
        - DEBUG=True
        - HERITRIX_CONTACT_URL=http://library.gwu.edu
    volumes_from:
        - sfmheritrix
    restart: always
sfmdata:
    image: ubuntu:14.04
    command: /bin/true
    volumes:
         - /sfm-data