sfmmasterrabbit:
    image: rabbitmq:3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=sfm_user
    env_file:
        - ./secrets.env
sfmmasterdb:
    image: gwul/sfm-ui-db:master
    env_file:
        - ./secrets.env
    restart: always
sfmmasterapp:
    image: gwul/sfm-ui:master
    ports:
        - "80:80"
    links:
        - sfmmasterdb:db
        - sfmmasterrabbit:mq
    environment:
        - SFM_DEBUG=True
        - SFM_SITE_ADMIN_EMAIL=nowhere@example.com
    restart: always
sfmmasterflickrharvester:
    image: gwul/sfm-flickr-harvester:master
    links:
        - sfmmasterrabbit:mq
    restart: always
    environment:
        - DEBUG=True
sfmmastertwitterrestharvester:
    image: gwul/sfm-twitter-rest-harvester:master
    links:
        - sfmmasterrabbit:mq
    restart: always
    environment:
        - DEBUG=True
sfmmastertwitterstreamharvester:
    image: gwul/sfm-twitter-stream-harvester:master
    links:
        - sfmmasterrabbit:mq
    restart: always
    environment:
        - DEBUG=True
