sfmrabbit:
    image: rabbitmq@sha256:a5180a37b0baebb938ee9d12dd11eed64a909288d7f344e24771278f8a122367
    #RabbitMQ 3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - TZ=EST
        - RABBITMQ_DEFAULT_USER=sfm_user
    env_file:
        - ./secrets.env
sfmuidb:
    image: gwul/sfm-ui-db:0.5.0
    env_file:
        - ./secrets.env
    environment:
        - TZ=EST
    restart: always
sfmuiapp:
    image: gwul/sfm-ui:0.5.0
    ports:
        - "80:80"
    links:
        - sfmuidb:db
        - sfmrabbit:mq
    environment:
        - TZ=EST
        - SFM_DEBUG=False
        - SFM_HOST=sfm.gwu.edu:8080
        - SFM_SMTP_HOST=smtp.gmail.com
        - SFM_EMAIL_USER=justinlittman@email.gwu.edu
        - SFM_EMAIL_PASSWORD=password
        - SFM_SITE_ADMIN_EMAIL=nowhere@example.com
    restart: always
    volumes_from:
        - sfmdata
sfmmflickrharvester:
    image: gwul/sfm-flickr-harvester:0.4.0
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=EST
        - DEBUG=False
    volumes_from:
        - sfmdata
#sfmflickrexporter:
#    image: gwul/sfm-flickr-exporter:X.X.X
#    links:
#        - sfmrabbit:mq
#        - sfmuiapp:api
#    restart: always
#    environment:
#        - DEBUG=False
#    volumes_from:
#        - sfmdata
sfmtwitterrestharvester:
    image: gwul/sfm-twitter-rest-harvester:0.3.0
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=EST
        - DEBUG=False
    volumes_from:
        - sfmdata
sfmtwitterstreamharvester:
    image: gwul/sfm-twitter-stream-harvester:0.3.0
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=EST
        - DEBUG=False
    volumes_from:
        - sfmdata
sfmweiboharvester:
    image: gwul/sfm-weibo-harvester:0.2.1
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=EST
        - DEBUG=False
    volumes_from:
        - sfmdata
#sfmheritrix:
#    image: gwul/sfm-heritrix:X.X.X
#    ports:
#        - "8443:8443"
#    env_file:
#        - ./secrets.env
#    environment:
#        - TZ=EST
#    volumes_from:
#        - sfmdata
#    restart: always
#sfmwebharvester:
#    image: gwul/sfm-web-harvester:X.X.X
#    links:
#        - sfmrabbit:mq
#        - sfmheritrix:heritrix
#    environment:
#        - TZ=EST
#        - DEBUG=False
#        - HERITRIX_CONTACT_URL=http://library.gwu.edu
#    volumes_from:
#        - sfmheritrix
#    restart: always
sfmdata:
    image: ubuntu:14.04
    command: /bin/true
    volumes:
         - /sfm-data
