sfmrabbit:
    image: rabbitmq@sha256:397382d2b222f3a298a6c74e93f348fb16f9a7fde2c02ba14122624d852daae3
    #RabbatMQ 3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=sfm_user
    env_file:
        - ./secrets.env
sfmuidb:
    image: gwul/sfm-ui-db:0.3.1
    env_file:
        - ./secrets.env
    restart: always
sfmuiapp:
    image: gwul/sfm-ui:0.3.1
    ports:
        - "80:80"
    links:
        - sfmuidb:db
        - sfmrabbit:mq
    environment:
        - SFM_DEBUG=False
        - SFM_SITE_ADMIN_EMAIL=nowhere@example.com
    restart: always
    volumes_from:
        - sfmdata
sfmmflickrharvester:
    image: gwul/sfm-flickr-harvester:0.2.0
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - DEBUG=False
    volumes_from:
        - sfmdata
sfmtwitterrestharvester:
    image: gwul/sfm-twitter-rest-harvester:0.1.1
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - DEBUG=False
    volumes_from:
        - sfmdata
sfmtwitterstreamharvester:
    image: gwul/sfm-twitter-stream-harvester:0.1.1
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - DEBUG=False
    volumes_from:
        - sfmdata
sfmdata:
    image: ubuntu:14.04
    command: /bin/true
    volumes:
         - /sfm-data